django/djangoweb/djangoweb/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from django.conf.urls import url

from boards import views
from accounts import views as account_view

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^signup/$', account_view.signup , name = "signup"),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name= "logout"),
    url(r'login/$',auth_views.LoginView.as_view(template_name = 'login.html'),name = 'login'),
    url(r'^$',views.home, name = 'home'),
    url(r'^homepage/$',views.home, name = 'home'), 
    url(r'^boards/(?P<pk>\d+)/$', views.board_topics, name = 'board_topics'),
    url(r'^boards/(?P<pk>\d+)/new/$',views.new_topic, name = 'new_topic')
]

django/djangoweb/accounts/models.py
from django.db import models

# Create your models here.

django/djangoweb/boards/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User


class Board(models.Model):
    name = models.CharField(max_length = 30, unique = True)
    description = models.CharField(max_length= 200 )
    
    def __str__(self):
        return self.name

    
class Topic (models.Model):
    subject  = models.CharField(max_length = 255 )
    last_updated = models.DateTimeField(auto_now_add = True)
    board = models.ForeignKey(Board, related_name= 'topics',on_delete=models.CASCADE)
    starter = models.ForeignKey(User, related_name= 'topics',on_delete=models.CASCADE)
    
    


class Post(models.Model):
    message = models.TextField(max_length= 4000)
    topic = models.ForeignKey(Topic,related_name = 'posts',on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add= True)
    Updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(User, related_name = 'posts',on_delete=models.CASCADE)
    updated_by = models.ForeignKey(User, null = True, related_name= '+',on_delete=models.CASCADE)
    

django/djangoweb/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User

# Create your views here.

def signup(request):
    return render(request, 'signup.html')

django/djangoweb/boards/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect,get_object_or_404
from .models import Board, Topic, Post

def home(request):
    boards = Board.objects.all()
    
    return render(request, 'home1.html',{'boards':boards})

def board_topics(request,pk):
    board = get_object_or_404(Board, pk= pk)
    return render(request, 'topic.html', {'board':board})

def new_topic(request,pk):
    board = get_object_or_404(Board,pk=pk)
    
    if request.method =='POST':
        subject = request.POST['subject']
        message = request.POST['message']
        
        user = User.objects.first() #TODO: get the currently logged in user
        
        topic = Topic.objects.create (subject = subject,  board = board , starter = user )
        post = Post.objects.create(message = message,topic = topic,created_by = user)
        return redirect('board_topics', pk = board.pk)
    
    return render(request,'newtopic.html',{'board':board})

django/djangoweb/templates/base.html
{% load static %} <!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <title>{% block title %}Django Boards{% endblock%} </title>
      <link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
      <link rel = "stylesheet" href="{% static 'css/app.css' %}">
    
      {% block stylesheet %} {% endblock %}
  </head>
  <body>
      {% block body %}
      <nav class = "navbar navbar-dark navbar-expand-lg bg-dark ">
 <div class="container ">
          <a class = "navbar-brand mr-auto" href = "{% url 'home' %}">Django Boards</a>
         
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainmenu" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="mainmenu">
      {% if user.is_authenticated %}
    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="username" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{user.username}}</a>
          
          <div class="dropdown-menu dropdown-menu-left" aria-labelledby="username">
          <a class="dropdown-item" href="#">My Account</a>
              <a class="dropdown-item" href="#">Change Password</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href=" {% url 'logout'%} ">Log out</a>
          </div>
          
      </li>
      </ul>
      {% else %}
      <form class="form-inline ml-auto">
      <a href = "{% url 'login'%}" class="btn btn-outline-secondary">Log in</a>
          <a href="{% url 'signup'%}" class="btn btn-primary ml-3">Sign up</a>
      </form>
      
      {% endif %}
          </div>
          </div> 
      
      </nav>
   <div class = "container ">
    <nav aria-label="breadcrumb">
  <ol class="breadcrumb my-4 ">
   {% block breadcrumb %} {% endblock%}
  </ol>
</nav>
       {% block content %}
       
       {% endblock%}

      </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
      {% endblock body%}
  </body>
</html>

django/djangoweb/templates/home.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset = "utf-8">
        <title>Boards</title>
    </head>
    
    <body>
    <h1>Boards</h1>
        
        <table border="1">
        
            <thead> 
                <tr>
                    
                    <th>Board</th>
                    <th>Posts</th>
                    <th>Topics</th>
                    <th>Last Post</th>              
                </tr>
            
            </thead>
            <tbody>
            {% for board in boards%}
                <tr>
                    
                    <td>
                    {{board.name}}<br>
                    <small style = "color: #888">
                        {{board.description}}</small>                
                    </td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>                 
                </tr>
                {%endfor%}
            
            </tbody>
        </table>
        
        
        
    </body>
</html>

django/djangoweb/templates/home1.html
{% extends 'base.html'%}

{% block breadcrumb %}
<li class="breadcrumb-item active " aria-current="page"><a href =" {% url 'home' %}">Boards</a></li>
{% endblock%}

{%block content %}
<table class="table">
  <thead class="thead-dark">
    <tr>
     
      <th scope="col">Boards</th>
      <th scope="col">Topics</th>
      <th scope="col">Posts</th>
    <th scope="col">Last Post</th>
    </tr>
  </thead>
  <tbody>
      {%for board in boards%}
    <tr>
      <td class="d-block align-middle">
        <a href = "{% url 'board_topics' board.pk %}">{{board.name}}</a><br>
          <small class= "text-muted">{{board.description}}</small>
        </td>
        <td class = "align-middle">0</td>
      <td class = "align-middle">0</td>
        <td class = "align-middle"></td>
    </tr>
      {%endfor%}
    
  </tbody>
</table>
{%endblock%}
       
       

      </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </body>
</html>

django/djangoweb/templates/newtopic.html
{% extends 'base.html'%}



{% block title%} Start a new Topic{% endblock%}


{%block breadcrumb %}
<li class="breadcrumb-item " ><a href = "{% url 'home' %}">Boards</a></li>
      <li class = "breadcrumb-item">{{board.name}}</li>
<li class="breadcrumb-item active">New Topic</li>
{%endblock%}

{% block content%}
<form method = "post">
{%csrf_token%}
    <div class = "form-group">
    <label for="id_subject">Subject</label>
        <input type = "text" class = "form-control" id = "id_subject" name = "subject">
    </div>
    <div class="form-group">
    <label for="id_message" >Message</label>
    <textarea class="form-control" id = "id_message" name = "message" rows = "5"></textarea>
    </div>
    <button type = "submit" class= "btn btn-success">Post</button>
</form>

{%endblock%}

django/djangoweb/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block title%}Sign Up{% endblock %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/account.css'%}">
{% endblock %}

{% block body %}

<div class="conatiner justify-content-center">
<h1 class="logo text-center my-4"><a href = "{% url 'home'%}">Django Boards</a></h1>
    <div class="row justify-content-center">
    <div class="signup-card col-lg-8 col-md-10 col-sm-12 justify-content-center">
        <div class="card mb-4 justify-content-center">
        <div class="card-body">
            <h5 class="card-title font-weight-bold">Sign Up</h5>
            <form method="post">
                <div class="from-group font-weight-bold">
                <label for="id_username">Username:</label>
                    <input type= "text" class="form-control" id = "id_username" name = "username">
                </div>
            <div class="form-group">
                <label for="id_Emailid">Email address:</label>
                <input type="email" class="form-control" id="id_Emailid" name="emailid">
                </div>
                <div class="form-group">
                <label for="id_password">Password</label>
                    <input type="password" class="form-control" id="id_password" name="password">
                </div>
                <div class="form-group">
                    <label for="id_passwordconf">Password Confirmation:</label>
                    <input type="password" class="form-control" id="id_passwordconf" name="passwordconfirmation">
                </div>
            <div class="form-group">  
                <button type="submit" class="btn btn-primary btn-block">Create Account</button>
                </div>          
                </form>
            
        <div class="card-footer text-muted text-center">Already have an account?<a href="#">Log In </a></div>
            </div>
        
        </div>
        
        </div>
    </div>

</div>

{%endblock%}

django/djangoweb/templates/topic.html
{% extends 'base.html'%}



{% block title%} {{board.name}}-{{block.super}}{% endblock%}


{%block breadcrumb %}
<li class="breadcrumb-item " ><a href = "{% url 'home' %}">Boards</a></li>
      <li class = "breadcrumb-item active">{{board.name}}</li>
{%endblock%}

{% block content%}
<div class = "my-4">
<a class="btn btn-primary" href = "{% url 'new_topic' board.pk %}">New Topic</a>
</div>
<table class="table">
  <thead class="thead-dark">
    <tr>
     
      <th scope="col">Topic</th>
      <th scope="col">Starter</th>
      <th scope="col">Replies</th>
    <th scope="col">Views</th>
        <th>Last Update</th>
    </tr>
  </thead>
  <tbody>
      {%for topic in board.topics.all%}
    <tr>
      <td>{{ topic.subject}}  </td>
      <td>{{ topic.starter.username}}</td>
      <td>0</td>
        <td>0</td>
        <td> {{topic.last_updated}}</td>
    </tr>
      {%endfor%}
    
  </tbody>
</table>

{%endblock%}